title: Michael Curran # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst with Diverse Expertise <br><br>
  Transitioning from marketing and project management to data analytics, I offer: <br>
  - Extensive experience in dynamic business environments <br>
  - Strong problem-solving and stakeholder collaboration skills <br>
  - Data visualization and statistical modeling expertise <br>
  - Proven track record of developing customer-aligned strategies <br><br>
  
  Former Naval Officer bringing leadership and discipline to projects. <br>
  Seeking a data analyst role to leverage my diverse skill set and drive impactful business decisions through data.  <br><br>
  <a href="https://www.linkedin.com/in/mikecurran09">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
